#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MonoDroid.Resource", IsApplication=true)]

namespace MonoDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int style_bottom_tab_bar_item_text_color = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int style_bottom_tab_bar_item_drawable_padding = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int style_bottom_tab_bar_item_margin_top = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int style_bottom_tab_bar_item_padding_top = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int style_bottom_tab_text_size = 2131034113;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int image1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int image2 = 2130837506;
			
			// aapt resource value: 0x7f020004
			public const int style_bottom_tab_bar_background_color = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int style_bottom_tab_bar_item_background = 2130837509;
			
			// aapt resource value: 0x7f020003
			public const int style_bottom_tab_bar_item_background_selector = 2130837507;
			
			// aapt resource value: 0x7f020006
			public const int style_bottom_tab_bar_item_checked_background = 2130837510;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090001
			public const int activity_actionbarmenu_textview = 2131296257;
			
			// aapt resource value: 0x7f090012
			public const int activity_main_list_item_imageview = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int activity_main_list_item_textview = 2131296275;
			
			// aapt resource value: 0x7f090000
			public const int fragment_actionbar_tabs_viewpager = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int fragment_animations_layout_animation_button = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int fragment_animations_layout_animation_imageview = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int fragment_animations_layout_animation_linear_layout = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int fragment_animations_layout_animation_textview = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int fragment_animations_property_animation_seekbar1 = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int fragment_animations_property_animation_seekbar2 = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public const int fragment_animations_view_animation_button = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int fragment_animations_view_animation_imageView = 2131296265;
			
			// aapt resource value: 0x7f090002
			public const int fragment_animations_viewpager = 2131296258;
			
			// aapt resource value: 0x7f090011
			public const int fragment_collection_demo_pager_itle_strip = 2131296273;
			
			// aapt resource value: 0x7f090010
			public const int fragment_collection_demo_viewpager = 2131296272;
			
			// aapt resource value: 0x7f090015
			public const int fragment_navigation_button = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int fragment_navigation_edittext = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int fragment_navigation_target_textview = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int fragment_pager_tabstrip_viewpager = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int fragment_pagertabstrip_tabstrip = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int fragment_popup_menu_button = 2131296281;
			
			// aapt resource value: 0x7f09000b
			public const int frameLayout1 = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int radioButton1 = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int radioButton2 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int radioButton3 = 2131296271;
			
			// aapt resource value: 0x7f09000c
			public const int radioGroup1 = 2131296268;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_actionbar_tabs = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_actionbar_tabs_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_actionbarmenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_animations = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_animations_layout_animation = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_animations_property_animation = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_animations_view_animation = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int fragment_bottom_tabbar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int fragment_collection_demo = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int fragment_collection_object = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int fragment_menu_list_item = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int fragment_navigation = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int fragment_navigation_target = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int fragment_pager_tabstrip_tabs = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int fragment_popup_menu = 2130903054;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int fragment_actionbarmenu_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int fragment_popup_menu_popup = 2131230721;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int fragment_navigation_button_text = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int fragment_navigation_edittext_hint = 2131099649;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int bottom_tab_bar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int bottom_tab_bar_item = 2131165185;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
