#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("EffectiveNavigation.Resource", IsApplication=true)]

namespace EffectiveNavigation
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int DemoCollectionButton = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int DemoExternalActivityButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int DemoListNavButton = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Pager = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int PagerTitleStrip = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CollectionDemoActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentCollectionObject = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentSectionDummy = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FragmentSectionLaunchpad = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListNavigationActivityActionbarListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainActivity = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int AppName = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int DemoCollection = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int DemoExternalActivity = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int DemoListNavActivity = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int DummySectionText = 2130968577;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
