#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Cn.Beginor.MyFirstApp.Resource", IsApplication=true)]

namespace Cn.Beginor.MyFirstApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MessageEditText = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int MessageTextView = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int SendButton = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SecondActivity = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int MessageEditTextHint = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SendButtonText = 2130968577;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
