// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Cn.Beginor.MyFirstApp
{
	
	
	public partial class Resource
	{
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int CountryArray = 2131034112;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MessageEditText = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MessageTextView = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int SendButton = 2131099649;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MyListActivityItemLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SecondActivityLayout = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int MessageEditTextHint = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int SendButtonText = 2130968577;
			
			private String()
			{
			}
		}
	}
}
